# Generated by Django 4.1.5 on 2023-01-28 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPolicyVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_policy_base', models.FloatField()),
                ('premium_policy_base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.FloatField()),
                ('coverage_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='StateRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=2, unique=True)),
                ('flood_multiplier_percent', models.IntegerField()),
                ('monthly_tax_percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('indicator', 'Indicator'), ('base_flat', 'Base fee or discount'), ('base_multiplier', 'Percentage fee or discount')], max_length=16)),
                ('description', models.TextField(max_length=512)),
                ('default_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QuoteVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=1024)),
                ('value', models.FloatField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quote')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variable')),
            ],
            options={
                'unique_together': {('quote', 'variable')},
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='rate_model',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.DO_NOTHING, to='api.staterates', to_field='state'),
        ),
        migrations.AddField(
            model_name='quote',
            name='variables',
            field=models.ManyToManyField(through='api.QuoteVariable', to='api.variable'),
        ),
    ]
