# Generated by Django 4.1.5 on 2023-01-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('NY', 'New York'), ('CA', 'California'), ('TX', 'Texas')], max_length=2)),
                ('coverage_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='VariableSpecification',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('state_lookup', 'State Policy Lookup'), ('global_lookup', 'Global Policy Lookup'), ('simple', 'Simple Value')], max_length=16)),
                ('application', models.CharField(choices=[('multiplier', 'Multiplier'), ('additive', 'Additive')], max_length=16)),
                ('description', models.TextField(max_length=512)),
                ('default_value', models.FloatField(blank=True, null=True)),
                ('priority', models.IntegerField(default=10)),
                ('lookup_key', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=64)),
                ('scope', models.CharField(default='global', max_length=64)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('key', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='QuoteVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=1024, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='api.quote')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variablespecification')),
            ],
            options={
                'unique_together': {('quote', 'spec')},
            },
        ),
    ]
