# Generated by Django 4.1.5 on 2023-01-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='base_rate',
            new_name='policy_base',
        ),
        migrations.AddField(
            model_name='globalpolicyvariables',
            name='pet_premium',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
