# Generated by Django 4.1.5 on 2023-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_staterates_flood_multiplier_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
