# Generated by Django 4.1.5 on 2023-01-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quote_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variable',
            new_name='VariableSpecification',
        ),
        migrations.RenameField(
            model_name='quotevariable',
            old_name='variable',
            new_name='spec',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='variables',
        ),
        migrations.AlterUniqueTogether(
            name='quotevariable',
            unique_together={('quote', 'spec')},
        ),
    ]
