# Generated by Django 4.1.5 on 2023-01-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_variable_variablespecification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablespecification',
            name='default_value',
            field=models.FloatField(null=True),
        ),
    ]
