# Generated by Django 4.1.5 on 2023-01-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_variablespecification_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotevariable',
            name='notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quotevariable',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='api.quote'),
        ),
        migrations.AlterField(
            model_name='quotevariable',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variablespecification',
            name='default_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
