# Generated by Django 4.1.5 on 2023-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_quote_description_alter_quotevariable_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablespecification',
            name='priority',
            field=models.IntegerField(default=10),
        ),
    ]
